[package]
name = "marketdata-player"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clickhouse = "0.13.1"
fpdec = "0.11.0"
serde = { version = "1.0.215", features = ["derive"] }
tokio = { version = "1.41.1", features = ["full"] }
